//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int ID { get; set; }
        public string AddressName { get; set; }
        public Nullable<int> City_ID { get; set; }
        public Nullable<int> District_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string AddressDetail { get; set; }
    
        public virtual City City { get; set; }
        public virtual District District { get; set; }
        public virtual User User { get; set; }
    }
}
